In [7]:
# Dependencies and definitions
import random
import pandas as pd
import numpy as np
import requests
import json
import re
import gmaps
from config import gkey
#https://maps.googleapis.com/maps/api/place/nearbysearch/json?
#location=-33.8670522,151.1957362&radius=1500&type=restaurant&keyword=cruise&key=YOUR_API_KEY
# Configure gmaps
gmaps.configure(api_key=gkey)
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
# params = {
#      "location": "40.730610,-73.935242", 
#      #"radius": 15000,
#      "rankby": "distance",
#      "type": "restaurant",
#      "key": gkey,
#      }

In [8]:
# Setup empty response holder
cities_name = []
State = []
Latitude = []
Longitude = []
Place_ID = []
Price_range = []
Rating = []
Ratings_count = []
restaurant_name = []

In [13]:
# assemble url and make API request
# Lower 48 box 25 to 49 -125 to -67

for i in range(400):
    lat = random.uniform(25.000000001, 49.000000001)
    lng = random.uniform(-125.000000001, -67.000000001)
    
    ll_dot = str(lat) +', ' + str(lng)
    
    params = {
    "location": ll_dot,  
    "rankby": "distance",
    "type": "restaurant",
    "key": gkey,
    }
    
    response = requests.get(base_url, params=params).json()
    length_res = (len(response["results"]))
    #print(length_res)
    # extract results
    #print(ll_dot)
    # print(json.dumps(response, indent=4, sort_keys=True))
    try:        
        # Checked in json formatter there are 3-parent attribute         
        
                for j in range(len(response["results"])):
                                            
                    city_state=response["results"][j]["plus_code"]["compound_code"]
                    #print(city_state) 
                        
                    # Using Regular expression(Regex) for slicing city and state
                    x = re.findall("(\w*),", city_state)
                    #print(x)
                    city = x[0]
                    state = x[1]
                    #print(city)
                    #print(state)
                        
                    place_id = response["results"][j]["place_id"]
                    #print(place_id)
                    lat = response["results"][j]["geometry"]["location"]["lat"]
                    #print(lat)
                    lng = response["results"][j]["geometry"]["location"]["lng"]
                    #print(lng)
                    
                    try:
                        price_level = response["results"][j]["price_level"]
                        #print(str(price_level))
                    except:
                        price_level=0.0
                        #print("inside except"+str(price_level))
                        
                    try:
                        rating = response["results"][j]["rating"]
                        #print(str(rating))
                    except:
                        rating=0.0
                        #print("inside except"+str(rating))
                    
                    try:
                        user_ratings_total = response["results"][j]["user_ratings_total"]    
                        #print(str(user_ratings_total))    
                    except:
                        user_ratings_total=0
                        #print("inside except"+str(user_ratings_total)) 
                        
                    try:
                        restaurant = response["results"][j]["name"]    
                        #print(str(user_ratings_total))    
                    except:
                        restaurant="default"
                        #print("inside except"+str(restaurant_name)) 
                    
                        
                        # Empty string check  
                    if("" !=city and "" !=state and "" !=str(place_id) and "" !=str(lat) and "" !=str(lng)  
                       and "" !=str(price_level) and "" !=str(user_ratings_total)
                       and "" !=str(rating) and "" !=str(restaurant)):
                        cities_name.append(city)
                        State.append(state)
                        Place_ID.append(str(place_id))
                        Latitude.append(str(lat))
                        Longitude.append(str(lng))
                        Price_range.append(str(price_level))
                        Rating.append(str(rating))
                        Ratings_count.append(str(user_ratings_total))
                        restaurant_name.append(str(restaurant))
                        #print("inside")

                        
                    
                        
    except(KeyError, IndexError):
        print("Data not found. Skipping...")
        continue
    
print("-----------------------------")
print("Data Retrieval Complete")
print("-----------------------------")

Data not found. Skipping...
-----------------------------
Data Retrieval Complete
-----------------------------

In [15]:
# Create a data frame using data retrieved
food_ratings_df = pd.DataFrame({ 
                "City" : cities_name,
                "State" : State,
                "Restaurant_Name" :restaurant_name,
                "Place_ID" : Place_ID,
                "Price_Range" : Price_range,
                "Rating" : Rating,
                "Ratings_Count" : Ratings_count,
                "Lat" : Latitude,
                "Lng" : Longitude
})

#food_ratings_df.dropna(inplace=True)
food_ratings_df.head(10)
#food_ratings_df.count()

,City,State,Restaurant_Name,Place_ID,Price_Range,Rating,Ratings_Count,Lat,Lng
0,Venetia,PA,Lyn Palace resto,ChIJ5dJ-c_b_NIgRKlRis7WfXR0,0.0,0.0,0,40.286502,-80.0618509
1,Park,PA,Luciano's Pizza & Pasta,ChIJiZQtdCX5NIgRbdVyyR8tryM,2,4,255,40.2974278,-80.0450194
2,Township,PA,Honeymoon,ChIJn-p6j0n5NIgRi2P7lP-eK3A,0.0,4.3,118,40.29041489999999,-80.02881959999999
3,Park,PA,Subway,ChIJTdDj1kn5NIgRqEkTP9j_e0k,1,4.3,80,40.2924775,-80.0310485
4,Township,PA,Castle Tavern South,ChIJE816nkn5NIgRBggTcKYb2nQ,1,4.5,343,40.2911191,-80.02851679999999
5,Park,PA,7-Eleven,ChIJQe-WKUj5NIgRMTHszePOI20,1,3.6,11,40.2937068,-80.0310338
6,Park,PA,Trolley Stop Inn,ChIJJwykOkj5NIgRhEASiE-O2QY,1,4.4,551,40.2934281,-80.03030660000002
7,Township,PA,Hot Box Pizza & Wings,ChIJJQNR8Uz5NIgR-wmLhBUE5uE,1,3.7,75,40.2870688,-80.0237271
8,Township,PA,Ya Ya's Pizza,ChIJLcvi4kz5NIgR_Ovd8SOGMqo,2,4.1,139,40.2865145,-80.0227936
9,Finleyville,PA,Beach House Restaurant,ChIJmfdaJrv-NIgRnIKBTBv_jPg,1,4.5,211,40.27143059999999,-80.02091109999999

In [16]:
# Export the city data into a .csv.
food_ratings_df.to_csv("resturent_output_final.csv", index = False)

In [17]:
food_ratings_df.count()

City               940
State              940
Restaurant_Name    940
Place_ID           940
Price_Range        940
Rating             940
Ratings_Count      940
Lat                940
Lng                940
dtype: int64